// <auto-generated />
using System;
using BackDistribuidora.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BackDistribuidora.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("BackDistribuidora.Entidades.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("Nome");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("BackDistribuidora.Entidades.ItemVenda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PrecoCusto")
                        .HasColumnType("TEXT")
                        .HasColumnName("PrecoCusto");

                    b.Property<decimal>("PrecoVenda")
                        .HasColumnType("TEXT")
                        .HasColumnName("PrecoVenda");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantidade")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VendaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProdutoId");

                    b.HasIndex("VendaId");

                    b.ToTable("ItensVendas");
                });

            modelBuilder.Entity("BackDistribuidora.Entidades.Marca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("Nome");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("Marcas");
                });

            modelBuilder.Entity("BackDistribuidora.Entidades.MarcaCategoria", b =>
                {
                    b.Property<int>("MarcaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("MarcaId", "CategoriaId");

                    b.HasIndex("CategoriaId");

                    b.ToTable("MarcasCategorias");
                });

            modelBuilder.Entity("BackDistribuidora.Entidades.MovimentacaoEstoque", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataMovimentacao")
                        .HasColumnType("TEXT")
                        .HasColumnName("DataMovimentacao");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantidade")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Quantidade");

                    b.Property<int>("TipoTransacao")
                        .HasColumnType("INTEGER")
                        .HasColumnName("TipoMovimentacao");

                    b.Property<int>("TipoUnidade")
                        .HasColumnType("INTEGER")
                        .HasColumnName("TipoUnidade");

                    b.HasKey("Id");

                    b.HasIndex("ProdutoId");

                    b.ToTable("MovimentacoesEstoque", (string)null);
                });

            modelBuilder.Entity("BackDistribuidora.Entidades.PrecoVenda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("TEXT")
                        .HasColumnName("DataFim");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("TEXT")
                        .HasColumnName("DataInicio");

                    b.Property<decimal>("PrecoFardo")
                        .HasColumnType("TEXT")
                        .HasColumnName("ValorFardo");

                    b.Property<decimal>("PrecoUnitario")
                        .HasColumnType("TEXT")
                        .HasColumnName("ValorUnitario");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProdutoId", "DataFim");

                    b.ToTable("PrecosVendas", (string)null);
                });

            modelBuilder.Entity("BackDistribuidora.Entidades.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MarcaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("MarcaId");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("BackDistribuidora.Entidades.Venda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataVenda")
                        .HasColumnType("TEXT")
                        .HasColumnName("DataVenda");

                    b.HasKey("Id");

                    b.ToTable("Vendas", (string)null);
                });

            modelBuilder.Entity("BackDistribuidora.Entidades.ItemVenda", b =>
                {
                    b.HasOne("BackDistribuidora.Entidades.Produto", null)
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BackDistribuidora.Entidades.Venda", "Venda")
                        .WithMany("Itens")
                        .HasForeignKey("VendaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Venda");
                });

            modelBuilder.Entity("BackDistribuidora.Entidades.MarcaCategoria", b =>
                {
                    b.HasOne("BackDistribuidora.Entidades.Categoria", "Categoria")
                        .WithMany("MarcaCategorias")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackDistribuidora.Entidades.Marca", "Marca")
                        .WithMany("MarcaCategorias")
                        .HasForeignKey("MarcaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Marca");
                });

            modelBuilder.Entity("BackDistribuidora.Entidades.MovimentacaoEstoque", b =>
                {
                    b.HasOne("BackDistribuidora.Entidades.Produto", "Produto")
                        .WithMany("MovimentacoesEstoque")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Distribuidora.Back.Entidades.Object_Values.CustoProdutoValue", "PrecoUnitario", b1 =>
                        {
                            b1.Property<int>("MovimentacaoEstoqueId")
                                .HasColumnType("INTEGER");

                            b1.Property<decimal>("Valor")
                                .HasColumnType("TEXT")
                                .HasColumnName("PrecoCusto");

                            b1.HasKey("MovimentacaoEstoqueId");

                            b1.ToTable("MovimentacoesEstoque");

                            b1.WithOwner()
                                .HasForeignKey("MovimentacaoEstoqueId");
                        });

                    b.Navigation("PrecoUnitario")
                        .IsRequired();

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("BackDistribuidora.Entidades.PrecoVenda", b =>
                {
                    b.HasOne("BackDistribuidora.Entidades.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("BackDistribuidora.Entidades.Produto", b =>
                {
                    b.HasOne("BackDistribuidora.Entidades.Categoria", "Categoria")
                        .WithMany("Produtos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackDistribuidora.Entidades.Marca", "Marca")
                        .WithMany("Produtos")
                        .HasForeignKey("MarcaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("Distribuidora.Back.Entidades.Object_Values.CustoProdutoValue", "PrecoCusto", b1 =>
                        {
                            b1.Property<int>("ProdutoId")
                                .HasColumnType("INTEGER");

                            b1.Property<decimal>("Valor")
                                .HasColumnType("TEXT")
                                .HasColumnName("PrecoCusto");

                            b1.HasKey("ProdutoId");

                            b1.ToTable("Produtos");

                            b1.WithOwner()
                                .HasForeignKey("ProdutoId");
                        });

                    b.OwnsOne("Distribuidora.Back.Entidades.Object_Values.EstoqueProdutoValue", "QuantidadeEstoque", b1 =>
                        {
                            b1.Property<int>("ProdutoId")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Valor")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER")
                                .HasDefaultValue(0)
                                .HasColumnName("QuantidadeEstoque");

                            b1.HasKey("ProdutoId");

                            b1.ToTable("Produtos");

                            b1.WithOwner()
                                .HasForeignKey("ProdutoId");
                        });

                    b.OwnsOne("Distribuidora.Back.Entidades.Object_Values.NomeProdutoValue", "NomeProduto", b1 =>
                        {
                            b1.Property<int>("ProdutoId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("TEXT")
                                .HasColumnName("Nome");

                            b1.HasKey("ProdutoId");

                            b1.ToTable("Produtos");

                            b1.WithOwner()
                                .HasForeignKey("ProdutoId");
                        });

                    b.OwnsOne("Distribuidora.Back.Entidades.Object_Values.QuantidadeFardoValue", "QuantidadeFardo", b1 =>
                        {
                            b1.Property<int>("ProdutoId")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Valor")
                                .HasColumnType("INTEGER")
                                .HasColumnName("QuantidadeFardo");

                            b1.HasKey("ProdutoId");

                            b1.ToTable("Produtos");

                            b1.WithOwner()
                                .HasForeignKey("ProdutoId");
                        });

                    b.Navigation("Categoria");

                    b.Navigation("Marca");

                    b.Navigation("NomeProduto")
                        .IsRequired();

                    b.Navigation("PrecoCusto")
                        .IsRequired();

                    b.Navigation("QuantidadeEstoque")
                        .IsRequired();

                    b.Navigation("QuantidadeFardo")
                        .IsRequired();
                });

            modelBuilder.Entity("BackDistribuidora.Entidades.Categoria", b =>
                {
                    b.Navigation("MarcaCategorias");

                    b.Navigation("Produtos");
                });

            modelBuilder.Entity("BackDistribuidora.Entidades.Marca", b =>
                {
                    b.Navigation("MarcaCategorias");

                    b.Navigation("Produtos");
                });

            modelBuilder.Entity("BackDistribuidora.Entidades.Produto", b =>
                {
                    b.Navigation("MovimentacoesEstoque");
                });

            modelBuilder.Entity("BackDistribuidora.Entidades.Venda", b =>
                {
                    b.Navigation("Itens");
                });
#pragma warning restore 612, 618
        }
    }
}
